image_dir: data/raw/training_data
#output_path: output/aligner/
checkpoints_path: checkpoints/
max_epochs: 100
batch_size: 8
learning_rate: 1e-3
data_type: quadrant_enumeration
n_teeth: 32
target_size: [ 1536, 3139 ]