# Data
image_dir: data/raw/training_data
output_path: output/
checkpoints_path: checkpoints/vision_transformer/
data_type: quadrant_enumeration_disease # quadrant | quadrant_enumeration | quadrant_enumeration_disease
n_classes: 5


# Model
max_epochs: 200
batch_size: 64
learning_rate: 1e-4
vit_version: 16