# Data
image_dir: data/raw/training_data
output_path: output/
checkpoints_path: checkpoints/vgg/
data_type: quadrant_enumeration_disease # quadrant | quadrant_enumeration | quadrant_enumeration_disease
n_classes: 4


# Model
max_epochs: 200
batch_size: 32
learning_rate: 1e-3
vgg_version: 16