# Data
output_path: output/
checkpoints_path: checkpoints/vgg/
n_classes: 1
unet_checkpoint: checkpoints/unet/version_67/checkpoints/epoch=epoch=84-val_loss=val_loss=0.32.ckpt

# Model
max_epochs: 100
batch_size: 32
learning_rate: 1e-4
vgg_version: 16